### ISSUE TITLE
Fill color looks like it's applied more than once when adding data to a chart that has no data

### ISSUE THREAD

**Issue by joaopaulobdac** [leeoniya/uPlot#359]
The title may be confusing, I couldn't figure out a better way to word this.

[Here's a codesandbox link demonstrating what is happening](https://codesandbox.io/s/uplot-130-fill-color-fhy8n?file=/src/index.js). The plot is initialized with no data. After adding some data for the first time, the series fill color seems more opaque than it should be. Then, after adding more data again the color is rendered normally.

This started happening since 1.3.0

**Comment by leeoniya** [comment]
huh, it looks like it triggers drawPath() twice.

**Comment by leeoniya** [comment]
the problematic section appear to be below, where it re-queues a redraw after an overly-eager assertion than an axis has been toggled on/off as a result of data change. gotta add more conditions to this part, but still have to figure out which.

https://github.com/leeoniya/uPlot/blob/04a345bfbca190bfc95900d91733d99e3030fad3/src/uPlot.js#L1316-L1329

**Comment by leeoniya** [comment]
should be fixed now. hopefully this bit doesn't cause superfluous redraws in other scenarios. i did some testing with the demos and it looks clean otherwise. 🤞

**Comment by joaopaulobdac** [comment]
Thank you for looking into this so quickly. I just cloned master and tried it, #358 got fixed indeed :pray: , but I'm afraid this one is still happening. Can you reopen this?

**Comment by leeoniya** [comment]
are you sure? i'm testing with this:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Fill Bug</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../dist/uPlot.min.css">
    <style>
      .u-under {
        background: #eee;
      }
    </style>
  </head>
  <body>
    <script src="../dist/uPlot.iife.js"></script>
    <script>
      const plotData = [[], []];

      const plot = new uPlot(
        {
        width: 640,
        height: 480,
        series: [
          {},
          {
          fill: "rgba(255, 0, 0, 0.5)"
          }
        ]
        },
        plotData,
        document.body
      );

      setTimeout(() => {
        plot.setData([
          [1604698342, 1604698347, 1604698352, 1604698357],
          [128, 64, 32, 16]
        ]);
      }, 1000);

      setTimeout(() => {
        plot.setData([
          [1604698342, 1604698347, 1604698352, 1604698357, 1604698362],
          [128, 64, 32, 16, 8]
        ]);
      }, 2000);
    </script>
  </body>
</html>
```

**Comment by joaopaulobdac** [comment]
:thinking:

I tried your html file and confirmed you're right, but if you set the plot size before setting the data, like this:
```js
setTimeout(() => {
    plot.setSize({ width: 641, height: 481 });
    plot.setData([
        [1604698342, 1604698347, 1604698352, 1604698357],
        [128, 64, 32, 16]
    ]);
}, 1000);

setTimeout(() => {
    plot.setData([
        [1604698342, 1604698347, 1604698352, 1604698357, 1604698362],
        [128, 64, 32, 16, 8]
    ]);
}, 2000);
```
the bug happens again!

**Comment by leeoniya** [comment]
i think making it bulletproof might be pretty difficult. i'll take a look tomorrow.

**Comment by leeoniya** [comment]
until i figure out exactly what to do here. you should use `u.batch()` to do consecutive expensive ops, which also fixes the issue:

```js
plot.batch(() => {
  plot.setSize({ width: 641, height: 481 });
  plot.setData([
  	[1604698342, 1604698347, 1604698352, 1604698357],
  	[128, 64, 32, 16]
  ]);
});
```

**Comment by joaopaulobdac** [comment]
It also draws twice if some reason you `setData` with no data
```js
setTimeout(() => {
    plot.setData([
        [],
        []
    ]);
}, 1000);

setTimeout(() => {
    plot.setData([
        [1604698342, 1604698347, 1604698352, 1604698357],
        [128, 64, 32, 16]
    ]);
}, 2000);

setTimeout(() => {
    plot.setData([
        [1604698342, 1604698347, 1604698352, 1604698357, 1604698362],
        [128, 64, 32, 16, 8]
    ]);
}, 3000);
```

**Comment by joaopaulobdac** [comment]
Actually, it's when you set data to the same data, or size to the same size.
This also draws twice:
```js
setTimeout(() => {
    plot.setSize({ width: 640, height: 480 });
}, 1000);

setTimeout(() => {
    plot.setData([
        [1604698342, 1604698347, 1604698352, 1604698357],
        [128, 64, 32, 16]
    ]);
}, 2000);

setTimeout(() => {
    plot.setData([
        [1604698342, 1604698347, 1604698352, 1604698357, 1604698362],
        [128, 64, 32, 16, 8]
    ]);
}, 3000);
```

@leeoniya I managed to fix it by 
```js
if (plot.width !== width && plot.height !== height) {
    plot.setSize({ width, height })
}

if (plotData !== plot.data) {
    plot.setData(plotData)
}
```
maybe this is all you need?

**Comment by leeoniya** [comment]
this is fixed by the new deferred rendering strategy: f838d114b847a7c2715b110015251a3ad2407836
